### ISSUE TITLE
Russian Insults

### ISSUE THREAD

**Issue by DaboFreezey** [lobobabysaurus/Filbot#5]
“schas po ebalu poluchish, suka, blyad!” (now i’ll fucking kill you bitch, motherfucker!)

Гандон/Gan-don
Literal meaning: condom

BUNCH OF MORONS, LIKE “SHEEPLE” (БЫДЛО, BYDLO)

IDIOT (ДУРАК, DURAK)

SWINE (СВОЛОЧЬ, SVOLOCH’)

LOWLIFE the drink leavings one (ПОДОНОК, PODONOK)

TRASH (ДРЯНЬ, DRIAN’)

Сволочь/Svo-lach‘

Literal meaning: scum; jerk
(Dragged in with the trash)

**Comment by lobobabysaurus** [comment]
Added support for most of these as a reaction to anybody saying the letters BOT in any case anywhere in a sentence
